# Generated by Django 4.2.14 on 2024-08-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoice',
            name='recipe_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
