# Generated by Django 4.2.14 on 2024-07-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notice_images/', verbose_name='공지 이미지'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='이미지'),
        ),
    ]
