# Generated by Django 4.2.14 on 2024-07-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='자유게시판 이미지'),
        ),
    ]
