# Generated by Django 4.2.14 on 2024-08-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
