# Generated by Django 4.2.14 on 2024-08-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycle',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
