# Generated by Django 4.2.14 on 2024-08-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycle',
            name='category',
            field=models.CharField(choices=[('trash', '일반쓰레기'), ('vinyl', '비닐류'), ('plastic', '플라스틱'), ('can', '병*캔류'), ('paper', '종이류'), ('food', '음식물쓰레기'), ('clothing', '의류수거함'), ('others', '기타')], max_length=20),
        ),
    ]
