# Generated by Django 4.2.14 on 2024-07-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interiorpost',
            name='category',
            field=models.CharField(blank=True, choices=[('modern', 'Modern'), ('classic', 'Classic'), ('industrial', 'Industrial'), ('scandinavian', 'Scandinavian'), ('bohemian', 'Bohemian')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interiorpost',
            name='furniture_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
