# Generated by Django 4.2.14 on 2024-07-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interiorpost',
            name='category',
            field=models.CharField(blank=True, choices=[('modern', 'Modern'), ('classic', 'Classic'), ('industrial', 'Industrial'), ('scandinavian', 'Scandinavian'), ('bohemian', 'Bohemian')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interiorpost',
            name='furniture_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interiorpost',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='interiorpost',
            name='image',
            field=models.ImageField(upload_to='interior_images/', verbose_name='인테리어 이미지'),
        ),
        migrations.AlterField(
            model_name='interiorpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
    ]
